// Code generated by osa/gen. DO NOT EDIT.
package osa_test

import (
	"github.com/echocrow/osa"
	"io"
	"io/fs"
)

type gbl struct{}

// Open opens the named file.
func (gbl) Open(name string) (fs.File, error) {
	return osa.Open(name)
}

// Lstat returns a FileInfo describing the named file.
func (gbl) Stat(name string) (FileInfo, error) {
	return osa.Stat(name)
}

// IsExist returns a boolean indicating whether the error is known to report
// that a file or directory already exists.
func (gbl) IsExist(err error) bool {
	return osa.IsExist(err)
}

// IsNotExist returns a boolean indicating whether the error is known to
// report that a file or directory does not exist.
func (gbl) IsNotExist(err error) bool {
	return osa.IsNotExist(err)
}

// PathSeparator returns the directory separator character.
func (gbl) PathSeparator() uint8 {
	return osa.PathSeparator()
}

// IsPathSeparator reports whether c is a directory separator character.
func (gbl) IsPathSeparator(c uint8) bool {
	return osa.IsPathSeparator(c)
}

// Mkdir creates a new directory.
func (gbl) Mkdir(name string, perm FileMode) error {
	return osa.Mkdir(name, perm)
}

// MkdirAll creates a directory named path, along with any necessary parents.
func (gbl) MkdirAll(name string, perm FileMode) error {
	return osa.MkdirAll(name, perm)
}

// MkdirTemp creates a new temporary directory in the directory dir and
// returns the pathname of the new directory.
func (gbl) MkdirTemp(dir, pattern string) (string, error) {
	return osa.MkdirTemp(dir, pattern)
}

// ReadDir reads the named directory and returns all its directory entries
// sorted by filename.
func (gbl) ReadDir(name string) ([]DirEntry, error) {
	return osa.ReadDir(name)
}

// WriteFile writes data to the named file, creating it if necessary.
func (gbl) WriteFile(name string, data []byte, perm FileMode) error {
	return osa.WriteFile(name, data, perm)
}

// ReadFile reads the named file and returns the contents.
func (gbl) ReadFile(name string) ([]byte, error) {
	return osa.ReadFile(name)
}

// Rename renames (moves) oldpath to newpath.
func (gbl) Rename(oldpath, newpath string) error {
	return osa.Rename(oldpath, newpath)
}

// Remove removes the named file or empty directory.
func (gbl) Remove(name string) error {
	return osa.Remove(name)
}

// RemoveAll removes path and any children it contains
func (gbl) RemoveAll(path string) error {
	return osa.RemoveAll(path)
}

// Getwd returns a rooted path name corresponding to the current directory.
func (gbl) Getwd() (dir string, err error) {
	return osa.Getwd()
}

// UserCacheDir returns the default directory to use for cached data.
func (gbl) UserCacheDir() (string, error) {
	return osa.UserCacheDir()
}

// UserConfigDir returns the default directory to use for configuration data.
func (gbl) UserConfigDir() (string, error) {
	return osa.UserConfigDir()
}

// UserHomeDir returns the current user's home directory.
func (gbl) UserHomeDir() (string, error) {
	return osa.UserHomeDir()
}

// Exit causes the current program to exit with the given status code.
func (gbl) Exit(code int) {
	osa.Exit(code)
}

// Stdin returns IO reader for Stdin.
func (gbl) Stdin() io.Reader {
	return osa.Stdin
}

// Stdout returns IO writer for Stdout.
func (gbl) Stdout() io.Writer {
	return osa.Stdout
}

// Stderr returns IO writer for Stderr.
func (gbl) Stderr() io.Writer {
	return osa.Stderr
}
